apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: console
spec:
  path: /
  to:
    kind: Service
    name: pacman
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
