apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pacman
spec:
  path: /
  to:
    kind: Service
    name: pacman
  #port:
  #  targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
