apiVersion: v1
kind: Route
metadata:
  name: pacman
spec:
  path: "/"
  to:
    kind: Service
    name: pacman
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None